export {default as logo} from "./common/sidenav/logo.svg"
export {default as drawer} from "./common/sidenav/drawer.svg"
export {default as dashboardIcon} from "./common/sidenav/dashboard-icon.svg"
export {default as graphIcon} from "./common/sidenav/graph-icon.svg"
export {default as historyIcon} from "./common/sidenav/history-icon.svg"
export {default as hospitalIcon} from "./common/sidenav/hospital-icon.svg"
export {default as organizationIcon} from "./common/sidenav/organization-icon.svg"
export {default as powerIcon} from "./common/sidenav/power-icon.svg"
export {default as setting2Icon} from "./common/sidenav/settings-2-icon.svg"
export {default as settingsIcon} from "./common/sidenav/settings-icon.svg"
export {default as profileIcon} from "./common/sidenav/profile-icon.svg"
export {default as cube} from "./card-icons/cube.svg"
export {default as graph} from "./card-icons/graph.svg"
export {default as people} from "./card-icons/people.svg"
export {default as calendar} from "./card-icons/calendar.svg"
export {default as clock} from "./card-icons/clock.svg"
export {default as organization} from "./card-icons/organization.svg"
export {default as facility} from "./card-icons/facility.svg"
export {default as spikeIcon} from "./common/global/spike-icon.svg"
export {default as spikeErrorIcon} from "./common/global/spike-error-icon.svg"
export {default as notificationIcon} from "./common/global/notification.svg"
export {default as manageResources} from "./footer/manage-resources.svg"
export {default as manageServices} from "./footer/manage-services.svg"
export {default as manageUsers} from "./footer/manage-users.svg"


